export const SEARCH_RESULTS_LOADING = 'SEARCH_RESULTS_LOADING';
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';
export const RESTAURANT_DETAILS_LOADING = 'RESTAURANT_DETAILS_LOADING';
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS';
export const RESTAURANT_DETAILS_FAILURE = 'RESTAURANT_DETAILS_FAILURE';
