POST http://localhost:5000/api/register
Content-Type: application/json

{
    "firstName": "Zhu",
    "lastName": "Li",
    "email": "zl@gmail.com",
    "password": "123456"
}
###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "zl@gmail.com",
    "password": "123456"
}
###
GET http://localhost:5000/api/search
Content-Type: application/json

{
    "geometry": { "type": "Point", "coordinates": [-73.99279, 40.719296] },
    "cuisine": "Indian"
}
###
POST http://localhost:5000/api/search
Content-Type: application/json

{
    "geometry": { "type": "Point", "coordinates": [-73.99279, 40.719296] }
}
###
GET http://localhost:5000/api/restaurant/5fab9241b9d43a2c3471da76
###
POST http://localhost:5000/api/saveOrder
Content-Type: application/json

{
    "restaurant": "5fab9241b9d43a2c3471da76",
    "email": "zl@gmail.com",
    "total": "45.00"
}
